#!/usr/bin/env bash

# command to reserve nodes:
#   oarsub -q production -p "cluster='grvingt'" -l nodes=32 -t allow_classic_ssh -I

# setup env for Chapel 1.24 using ofi
setupChplenv() {

  #module use /grid5000/spack/share/spack/modules/linux-debian9-x86_64/
  #module load gcc/6.4.0_gcc-6.4.0
  module load hal-deps
  module load libfabric

  # Ignore our errors about ofi/psm not being supported
  #export CHPL_GASNET_ALLOW_BAD_SUBSTRATE=true

  export CHPL_HOME="/lustre/projects/csa/dvm/dvm_runs/carnei26/chapel-2.1.0"

 # if [ -d "$CHPL_HOME" ]; then
    CHPL_BIN_SUBDIR=`"$CHPL_HOME"/util/chplenv/chpl_bin_subdir.py`
    export PATH="$PATH":"$CHPL_HOME/bin/$CHPL_BIN_SUBDIR:$CHPL_HOME/util"
 #fi

  export MANPATH="$MANPATH":"$CHPL_HOME"/man
  export CHPL_LLVM=system
  #export FI_PROVIDER=psm2

  # use gasnet-ofi -- from the psm docs "Users of Intel(R) Omni-Path Fabric are
  # recommended to use ofi-conduit"
  export CHPL_COMM='gasnet'
  export CHPL_COMM_SUBSTRATE='ibv'
  export CHPL_TARGET_CPU='native'
  export CHPL_LAUNCHER='gasnetrun_ibv'
  export GASNET_QUIET=1

  export GASNET_IBV_SPAWNER=ssh
  export GASNET_PHYSMEM_MAX='0.25'

  export CHOP_HOME=~/ChOp
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":"$CHOP_HOME"/libs

  # no idea if this is needed
  export HFI_NO_CPUAFFINITY=1

  # Use ssh spawning (and avoid mpi) -- I couldn't get mpi spawner working
  export CHPL_GASNET_MORE_CFG_OPTIONS="--enable-pshm"
  # TODO force psm provider
  #export GASNET_OFI_SPAWNER='ssh'

  NUM_T_LOCALE=$(cat /proc/cpuinfo | grep processor | wc -l)

  export CHPL_RT_NUM_THREADS_PER_LOCALE=$NUM_T_LOCALE




}

buildChpl() {
  setupChplenv
  pushd $CHPL_HOME
  nice make -j `nproc`
  make test-venv
  popd
}

setSSHServers() {
  export GASNET_SSH_SERVERS=$(uniq $PBS_NODEFILE | tr '\n' ' ')
}

setSSHServers
buildChpl
